"""empty message

Revision ID: 61d8f972ea00
Revises: ed2b348a391a
Create Date: 2020-02-17 12:26:14.010395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d8f972ea00'
down_revision = 'ed2b348a391a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('art', sa.String(length=255), nullable=True))
    op.drop_column('art', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('photo', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('art', 'art')
    # ### end Alembic commands ###
