"""empty message

Revision ID: ed2b348a391a
Revises: 6a85d638e0ba
Create Date: 2020-02-17 11:53:39.841768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2b348a391a'
down_revision = '6a85d638e0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('art', 'title')
    # ### end Alembic commands ###
